server:
  port: 8080

spring:
  application:
    name: person
  datasource:
    url: jdbc:mysql://localhost:6033/person
    username: ekklesia
    password: rootadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
